################################################################################
#
# kf5-kconfigwidgets
#
################################################################################

KF5_KCONFIGWIDGETS_VERSION = $(KF5_VERSION)
KF5_KCONFIGWIDGETS_SITE = $(KF5_SITE)
KF5_KCONFIGWIDGETS_SOURCE = kconfigwidgets-$(KF5_KCONFIGWIDGETS_VERSION).tar.xz
KF5_KCONFIGWIDGETS_LICENSE = BSD-3-Clause
KF5_KCONFIGWIDGETS_LICENSE_FILES = COPYING-CMAKE-SCRIPTS

KF5_KCONFIGWIDGETS_DEPENDENCIES = host-pkgconf kf5-kguiaddons kf5-ki18n kf5-kwidgetsaddons
KF5_KCONFIGWIDGETS_INSTALL_STAGING = YES
KF5_KCONFIGWIDGETS_SUPPORTS_IN_SOURCE_BUILD = NO
KF5_KCONFIGWIDGETS_CONF_OPTS = -DBUILD_DESIGNERPLUGIN=OFF

KF5_KCONFIGWIDGETS_CXXFLAGS = $(TARGET_CXXFLAGS)

ifeq ($(BR2_TOOLCHAIN_HAS_LIBATOMIC),y)
KF5_KCONFIGWIDGETS_CXXFLAGS += -latomic
endif

KF5_KCONFIGWIDGETS_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(KF5_KCONFIGWIDGETS_CXXFLAGS)"

$(eval $(cmake-package))
