#!/bin/sh
#
# Loading boot splash
#

start() {
	printf "Loading boot splash ..."
	cat /dev/zero 1> /dev/fb0 2>/dev/null
	fbv -f -d 1 /opt/mycroft/splash/boot.png > /dev/null 2>&1
	echo "[OK]"
}

case "$1" in
  start)
        start
        ;;
  *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?
