################################################################################
#
# mycroft-skill-better-playback-control
#
################################################################################

MYCROFT_SKILL_BETTER_PLAYBACK_CONTROL_VERSION = ba5bf157efb78736d4194cc8474542322f1b5d2f
MYCROFT_SKILL_BETTER_PLAYBACK_CONTROL_SITE = git://github.com/OpenVoiceOS/skill-better-playback-control
MYCROFT_SKILL_BETTER_PLAYBACK_CONTROL_SITE_METHOD = git
MYCROFT_SKILL_BETTER_PLAYBACK_CONTROL_DIRLOCATION = home/mycroft/.local/share/mycroft/skills
MYCROFT_SKILL_BETTER_PLAYBACK_CONTROL_DIRNAME = skill-better-playback-control

define MYCROFT_SKILL_BETTER_PLAYBACK_CONTROL_INSTALL_TARGET_CMDS
	mkdir -p $(TARGET_DIR)/$(MYCROFT_SKILL_BETTER_PLAYBACK_CONTROL_DIRLOCATION)/$(MYCROFT_SKILL_BETTER_PLAYBACK_CONTROL_DIRNAME)
	cp -dpfr $(@D)/* $(TARGET_DIR)/$(MYCROFT_SKILL_BETTER_PLAYBACK_CONTROL_DIRLOCATION)/$(MYCROFT_SKILL_BETTER_PLAYBACK_CONTROL_DIRNAME)
	cp -dpfr $(MYCROFT_SKILL_BETTER_PLAYBACK_CONTROL_DL_DIR)/git/.git* \
		$(TARGET_DIR)/$(MYCROFT_SKILL_BETTER_PLAYBACK_CONTROL_DIRLOCATION)/$(MYCROFT_SKILL_BETTER_PLAYBACK_CONTROL_DIRNAME)
endef

$(eval $(generic-package))
