#Dracut configuration

show_modules=no
i18n_install_all=no
lvmconf=no
mdadmconf=no
early_microcode=no
use_fstab=no
do_strip=no

# Dracut modules needed
add_dracutmodules+=" \
00-merged-usr \
dbus-daemon \
dm \
dmsquash-live \
dmsquash-live-autooverlay \
dracut-systemd \
libc-links \
overlayfs \
shell-interpreter \
systemd \
systemd-initrd \
systemd-journald \
systemd-modules-load \
systemd-sysctl \
systemd-tmpfiles \
systemd-udevd
"

# Modules to ignore
omit_dracutmodules+=" \
biosdevname \
btrfs \
caps \
cifs \
connman \
crypt \
crypt-gpg \
dbus-broker \
dmraid \
dmsquash-live-ntfs \
fcoe \
fcoe-uefi \
hwdb \
iscsi \
lvmmerge \
lvmthinpool-monitor \
lvm \
mdraid \
memstrack \
modsign \
multipath \
nbd \
network-legacy \
network-manager \
network-wicked \
nfs \
nvdimm \
nvmf \
parse-lunmask \
pcsc \
qemu \
qemu-net \
rngd \
ssh-client \
stratis \
systemd-ac-power \
systemd-bsod \
systemd-coredump \
systemd-cryptsetup \
systemd-hostnamed \
systemd-ldconfig \
systemd-networkd \
systemd-pcrphase \
systemd-portabled \
systemd-pstore \
systemd-sysext \
squash-squashfs \
tpm2-tss \
virtiofs \
"
