#Dracut configuration

show_modules=no
i18n_install_all=no
lvmconf=no
mdadmconf=no
early_microcode=no
hostonly=no
hostonly_cmdline=no
use_fstab=no
do_strip=no

# Dracut modules needed
add_dracutmodules+=" \
00-merged-usr \
bash \
bluetooth \
dash \
dbus \
dmsquash-live-autooverlay \
dracut-systemd \
systemd \
systemd-udevd \
systemd-timedated \
systemd-resolved \
systemd-initrd \
systemd-journald \
systemd-timesyncd \
systemd-modules-load \
systemd-sysctl \
systemd-repart \
systemd-sysusers \
systemd-tmpfiles
"

# Modules to ignore
omit_dracutmodules+=" \
biosdevname \
btrfs \
busybox \
caps \
cifs \
connman \
crypt \
crypt-gpg \
dbus-broker \
dmraid \
dmsquash-live-ntfs \
fcoe \
fcoe-uefi \
iscsi \
i18n \
lvmmerge \
lvm \
lvmthinpool-monitor \
lunmask \
mdraid \
memstrack \
mksh \
modsign \
mount-root \
multipath \
nbd \
network-legacy \
network-wicked \
nfs \
nvdimm \
nvmf \
pcsc \
parse-lunmask \
qemu \
qemu-net \
resume \
rngd \
systemd-bsod \
systemd-coredump \
systemd-cryptsetup \
systemd-hostnamed \
systemd-integritysetup \
systemd-networkd \
systemd-pcrphase \
systemd-portabled \
systemd-pstore \
systemd-sysext \
systemd-veritysetup \
squash \
squash-squashfs \
ssh-client \
stratis \
tpm2-tss \
url-lib \
usrmount \
virtiofs \
"
