#!/bin/sh
#
# Starts Mycroft services.
#

start() {
	printf "Starting Mycroft services: "
	umask 077
	bash /usr/bin/start-mycroft.sh all
	echo "OK"
}
stop() {
	printf "Stopping Mycroft services: "
	bash /usr/bin/stop-mycroft.sh all
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
