#!/bin/sh

# etc persistent overlay
if [ ! -d /mnt/overlay/etc ]; then
  mkdir -p /mnt/overlay/etc
  cp -a /etc/* /mnt/overlay/etc/
fi

# root home directory
if [ ! -d /mnt/overlay/root ]; then
  mkdir -p /mnt/overlay/root
fi
