#!/bin/sh
# Credits go to: https://github.com/home-assistant/operating-system/
set -e  # Exit on any command failure

# Options
TYPE=""
SIZE=0
MOUNT=""
DEVICE=""

# Parse arguments
while [ "$1" != "" ]; do
    key=$1
    case $key in
        -t|--type)
            TYPE=$2
            shift
            ;;
        -s|--size)
            SIZE=$2
            shift
            ;;
        -m|--mount)
            MOUNT=$2
            shift
            ;;
        *)
            echo "[Error] $0 : Argument '$1' unknown"
            exit 1
            ;;
    esac
    shift
done

# Validate Type
if [ "$TYPE" != "swap" ] && [ "$TYPE" != "fs" ]; then
    echo "Error: Type must be 'swap' or 'fs'"
    exit 1
fi

# Lookup device
if [ "$TYPE" = "swap" ]; then
    DEVICE="/dev/zram0"
elif [ "$MOUNT" = "var" ]; then
    DEVICE="/dev/zram1"
elif [ "$MOUNT" = "tmp" ]; then
    DEVICE="/dev/zram2"
else
    echo "Error: No device for lookup!"
    exit 1
fi

# Calculate 20% of memory for ZRAM swap partition if not specified
if [ "$TYPE" = "swap" ] && [ "$SIZE" -eq 0 ]; then
    SIZE=$(awk '/MemTotal/{ print int($2 * 0.20) }' /proc/meminfo)K
fi

# Initialize ZRAM device
zramctl "$DEVICE" -s "$SIZE" -a lz4

# Setup based on type
if [ "$TYPE" = "swap" ]; then
    mkswap -L "ovos-zramswap" "$DEVICE"
elif [ "$TYPE" = "fs" ]; then
    mkfs.ext4 -L "ovos-$MOUNT" -O ^has_journal "$DEVICE"
fi
