#!/bin/sh
#
# seeed-voicecard	Starts seeed-voicecard.
#

umask 077

start() {
	printf "Starting seeed-voicecard: "
	mount -t configfs none /sys/kernel/config
	/usr/bin/seeed-voicecard
	touch /var/lock/seeed-voicecard
	echo "OK"
}
stop() {
	printf "Stopping seeed-voicecard: "
	killall seeed-voicecard
	rm -f /var/lock/seeed-voicecard
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

