#!/bin/bash
#
# Copyright (c) 2018 Baozhu Zuo <zuobaozhu@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -x
exec 1>/var/log/$(basename $0).log 2>&1

OVERLAYS=/boot/overlays
#enable i2c interface
dtparam -d $OVERLAYS i2c_arm=on
modprobe i2c-dev

#enable spi interface
dtparam -d $OVERLAYS spi=on

CONFIG=/boot/config.txt
get_overlay() {
    ov=$1
    if grep -q -E "^dtoverlay=$ov" $CONFIG; then
      echo 0
    else
      echo 1
    fi
}

do_overlay() {
    ov=$1
    RET=$2
    DEFAULT=--defaultno
    CURRENT=0
    if [ $(get_overlay $ov) -eq 0 ]; then
        DEFAULT=
        CURRENT=1
    fi
    if [ $RET -eq $CURRENT ]; then
        ASK_TO_REBOOT=1
    fi
    if [ $RET -eq 0 ]; then
        sed $CONFIG -i -e "s/^#dtoverlay=$ov/dtoverlay=$ov/"
        if ! grep -q -E "^dtoverlay=$ov" $CONFIG; then
            printf "dtoverlay=$ov\n" >> $CONFIG
        fi
        STATUS=enabled
    elif [ $RET -eq 1 ]; then
        sed $CONFIG -i -e "s/^dtoverlay=$ov/#dtoverlay=$ov/"
        STATUS=disabled
    else
        return $RET
    fi
}


is_1a=$(i2cdetect -y  1 0x1a 0x1a | egrep "(1a|UU)" | awk '{print $2}')
is_35=$(i2cdetect -y  1 0x35 0x35 | egrep "(35|UU)" | awk '{print $2}')
is_3b=$(i2cdetect -y  1 0x3b 0x3b | egrep "(3b|UU)" | awk '{print $2}')

RPI_HATS="seeed-2mic-voicecard seeed-4mic-voicecard seeed-8mic-voicecard"
overlay=""

if [ "x${is_1a}" != "x" ] && [ "x${is_35}" == "x" ] ; then
    echo "install 2mic"
    overlay=seeed-2mic-voicecard
    asound_state=/etc/voicecard/wm8960_asound.state
    pulse_default=/etc/pulse/seeed-voicecard-2mic-default.pa
    pulse_daemon=/etc/pulse/seeed-voicecard-2mic-daemon.conf
fi

if [ "x${is_3b}" != "x" ] && [ "x${is_35}" == "x" ] ; then
    echo "install 4mic"
    overlay=seeed-4mic-voicecard
    asound_state=/etc/voicecard/ac108_asound.state
    pulse_default=/etc/pulse/seeed-voicecard-4mic-default.pa
    pulse_daemon=/etc/pulse/seeed-voicecard-4mic-daemon.conf
fi

if [ "x${is_3b}" != "x" ] && [ "x${is_35}" != "x" ] ; then
    echo "install 6mic"
    overlay=seeed-8mic-voicecard
    asound_state=/etc/voicecard/ac108_6mic.state
    pulse_default=/etc/pulse/seeed-voicecard-8mic-default.pa
    pulse_daemon=/etc/pulse/seeed-voicecard-8mic-daemon.conf
fi

if [ "$overlay" ]; then
    echo Install $overlay ...

    # Remove old configuration
    rm /var/lib/alsa/asound.state
    rm /etc/pulse/default.pa
    rm /etc/pulse/system.pa
    rm /etc/pulse/daemon.conf

    kernel_ver=$(uname -r)
    # echo kernel_ver=$kernel_ver

    # TODO: dynamic dtoverlay Bug of v4.19.x
    #       no DT node phandle inserted.
    if [[ "$kernel_ver" =~ ^4\.19.*$ || "$kernel_ver" =~ ^5\.*$ ]]; then
        for i in $RPI_HATS; do
            if [ "$i" == "$overlay" ]; then
                do_overlay $overlay 0
            else
                echo Uninstall $i ...
                do_overlay $i 1
            fi
        done
    fi
    #make sure the driver loads correctly
    dtoverlay -d $OVERLAYS $overlay || true

    #install soundstate
    echo "create $overlay asound status file"
    ln -s $asound_state /var/lib/alsa/asound.state

    #install pulseaudio files
    echo "create $overlay pulse default file"
    ln -s $pulse_default /etc/pulse/default.pa
    echo "create $overlay pulse system file"
    ln -s $pulse_default /etc/pulse/system.pa
    echo "create $overlay pulse daemon file"
    ln -s $pulse_daemon /etc/pulse/daemon.conf
fi

alsactl restore

touch /var/lock/seeed-voicecard
