################################################################################
#
# kf5-knotifications
#
################################################################################

KF5_KNOTIFICATIONS_VERSION = $(KF5_VERSION)
KF5_KNOTIFICATIONS_SITE = $(KF5_SITE)
KF5_KNOTIFICATIONS_SOURCE = knotifications-$(KF5_KNOTIFICATIONS_VERSION).tar.xz
KF5_KNOTIFICATIONS_LICENSE = BSD-3-Clause
KF5_KNOTIFICATIONS_LICENSE_FILES = COPYING-CMAKE-SCRIPTS

KF5_KNOTIFICATIONS_DEPENDENCIES = host-pkgconf kf5-phonon
KF5_KNOTIFICATIONS_INSTALL_STAGING = YES
KF5_KNOTIFICATIONS_SUPPORTS_IN_SOURCE_BUILD = NO

KF5_KNOTIFICATIONS_CXXFLAGS = $(TARGET_CXXFLAGS)

ifeq ($(BR2_TOOLCHAIN_HAS_LIBATOMIC),y)
KF5_KNOTIFICATIONS_CXXFLAGS += -latomic
endif

KF5_KNOTIFICATIONS_CONF_OPTS = -DCMAKE_CXX_FLAGS="$(KF5_KNOTIFICATIONS_CXXFLAGS)"

$(eval $(cmake-package))
