#!/bin/bash
#
set -x
exec 1>/var/log/$(basename $0).log 2>&1

mkdir -p /boot
mount -t vfat /dev/mmcblk0p1 /boot

echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

rm /var/lib/alsa/asound.state
rm /etc/pulse/default.pa
rm /etc/pulse/system.pa
rm /etc/pulse/daemon.conf

ln -s /var/lib/alsa/default-asound.state /var/lib/alsa/asound.state
ln -s /etc/pulse/pulseaudio-default.pa /etc/pulse/default.pa
ln -s /etc/pulse/pulseaudio-system.pa /etc/pulse/system.pa
ln -s /etc/pulse/pulseaudio-daemon.conf /etc/pulse/daemon.conf

export LC_ALL="C"

mkdir -p /etc/wpa_supplicant
if [ -f "/boot/wpa_supplicant.conf" ]; then
    mv /boot/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
    chmod 600 /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
fi
